const fs = require('fs');

// The error is in globals.css, but it's generated by Tailwind.
// The error says "Missed semicolon" at column 27992.
// This is typically a problem with an arbitrary value like `w-[calc(100%-20px)]`
// where the CSS parser gets confused.

// Let's search for arbitrary values with `calc` or `var` in the files we edited.
const { execSync } = require('child_process');

try {
  const output = execSync('grep -rE "class(Name)?=.*calc" src/app/').toString();
  console.log("calc() in classNames:", output);
} catch (e) {
  console.log("No calc() in classNames found.");
}

try {
  const output = execSync('grep -rE "class(Name)?=.*var" src/app/').toString();
  console.log("var() in classNames:", output);
} catch (e) {
  console.log("No var() in classNames found.");
}
